# -*- coding: utf-8 -*-
"""dataframe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rkia63L6FiJHKGfeRUNitscOb2lQuPwO
"""



import pandas as pd
df=pd.DataFrame({
"name":['a','b','c','d','e'],
"father_name":['ab','bc','cd','de','ac'],
"doy":[1980,1987,1970,1978,1975],
"status":['son','daughter','son','daughter','son']})
print(df)

df["age"]=2022-df['doy']
print(df)

df['fathers_age']=df['age']*2
df

df['fathers_status']=df['fathers_age'].apply(lambda x :'rtd' if x>80 else 'not rtd')
df

df['gender']=df['status'].apply(lambda y :'F' if y=='daughter' else 'M')
df
df.to_csv('dataframe.csv')

df=pd.read_csv('dataframe.csv')
df